// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDijrPS2ouRYQjFkX1I2oG_g034Te4UwSo',
    appId: '1:352896392153:web:9e66492a9df9a5cb6b57c8',
    messagingSenderId: '352896392153',
    projectId: 'blabber-7468d',
    authDomain: 'blabber-7468d.firebaseapp.com',
    storageBucket: 'blabber-7468d.appspot.com',
    measurementId: 'G-G7GFTHMCDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGU6-Tt45LqPc3BdA13oc_XdmAXwRMV4',
    appId: '1:352896392153:android:764b9f0ebce26d526b57c8',
    messagingSenderId: '352896392153',
    projectId: 'blabber-7468d',
    storageBucket: 'blabber-7468d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprEmCP7msL3DiqSjS_sxcRroayJzfZqE',
    appId: '1:352896392153:ios:f533fa56261860676b57c8',
    messagingSenderId: '352896392153',
    projectId: 'blabber-7468d',
    storageBucket: 'blabber-7468d.appspot.com',
    iosBundleId: 'com.example.blabber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDprEmCP7msL3DiqSjS_sxcRroayJzfZqE',
    appId: '1:352896392153:ios:7de3210bbf22b9e46b57c8',
    messagingSenderId: '352896392153',
    projectId: 'blabber-7468d',
    storageBucket: 'blabber-7468d.appspot.com',
    iosBundleId: 'com.example.blabber.RunnerTests',
  );
}
